### ISSUE TITLE
roadmap to playable

### ISSUE THREAD

**Issue by nanai10a** [raiga0310/Sort-Quiz#8]
## screens

- Start
- Play
- Result

## milestones

- [x] build environment
  - [x] initialize npm project
  - [x] setup builder
  - [ ] setup formatter, linter *?*
- [ ] complete implementation
  - [x] 初期状態を Start 画面とする
    - [x] 名前を入力させる
  - [x] Play 画面へ遷移する
    - [x] 言語ごとの情報を収集する #1
      - 言語名
      - 拡張子
      - 説明
      - リリース日付
    - [ ] カードを並べる
    - [ ] カードを並び替え可能にする #2
    - [ ] カードを再取得可能にする
  - [x] Result 画面へ遷移する #2
    - [x] 点数計算を行う #9
    - [x] 点数表示を行う #4
    - [ ] リーダーボードへの点数保存を行う #10
    - [x] リーダーボード表示を行う #9
  - [x] Start 画面へ遷移する #2
- [ ] adjust styling
  - [ ] Start 画面
  - [ ] Play 画面 #5, #7, ...
    - [x] 言語カード
      - [x] 表示
      - [x] アニメーション
    - [ ] 他説明的要素
  - [ ] Result 画面 #4, ...
- [ ] deploy / publish
  - [ ] *undetermined*
